### ISSUE TITLE
`closest_entity` always returns the same point fare from target point

### ISSUE THREAD

**Issue by alejoe91** [MiroK/nEuronMI#24]
When finiding the closest neuronal element (`closest_entity`), the closest point is always the same and far from the target point.

E.g. when running https://github.com/MiroK/nEuronMI/blob/get-stimul-area/sandbox/test_stim.py and setting the stimulation position to [0, 0, 30], the closest point found is [  -0.52113747,   -1.97246009,  188.72674425] (converted to um).

**Comment by MiroK** [comment]
Can you check now cd7ee33fc4c79f89acfaf6108c567c65c5651ec7

**Comment by alejoe91** [comment]
Thanks! It works :)
